#The world that the game will use, case sensitive.
map: game
#The max amount of eliminations before the game ends.
max-eliminations: 20
messages:
  waiting-tip: "Waiting for players..."
  countdown-tip: "Starting in: {TIME}"
  eliminated-player-tip: "&cEliminated {VICTIM_NAME}"
  eliminations-tip: "&cEliminations: &6{ELIMINATIONS}"
  no-one-won: "Game over, no one won."
  player-won: "{DISPLAY_NAME} won the game!"
#Timers for each game status.
timers:
  countdown: 15
  game: 900 # 15 minutes
  # Reset is when the game ends and as of right now, shuts down the server.
  reset: 5
